# Generated by Django 2.0.7 on 2020-03-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.CharField(choices=[('EUR', 'Евро'), ('USD', 'Доллары'), ('RUB', 'Рубли'), ('CZK', 'Кроны'), ('IDR', 'Рупии')], default='', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.CharField(choices=[('EUR', 'Евро'), ('USD', 'Доллары'), ('RUB', 'Рубли'), ('CZK', 'Кроны'), ('IDR', 'Рупии')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
    ]
